recommendations_for_webtoons/recommendationapp/urls.py
from django.urls import path
from . import views, views_service, views_static, views_account

app_name = 'rcmd'

urlpatterns = [
    path('manage_data', views.manage_data, name="md"),
    path('testpage', views.testpage, name='testpage'),
    
    # ===========================================================
    # ==================       TOP_PAGES        =================
    # ===========================================================
    
    path('search/', views_service.service_artwork, name='search'),
    path('search/<str:keyword>', views_service.service_artwork, name='search_result'),
    
    path('service/', views_service.main, name='service'),
    path('service/artwork/<str:artwork_id>/', views_service.service_artwork, name='service_artwork'),
    
    
    
    path('intro/', views_static.intro, name='intro'),
    
    path('about/', views_static.about, name='about'),
    
    # ===========================================================
    # ==================       Account_PAGES        =================
    # ===========================================================
    
    path('auth00/', views_account.join, name='join'),
    path('auth01/', views_account.log_in, name='log_in'),
    path('logout/', views_account.logout, name='logout'),
    # path('account/', views_account.log_out, name='account'),
    
    # path('account/', views_account.account_test, name='account'),
    path('sendemail/', views_account.sendemail, name='send_mail'),
#    path('registerauth/', views.register_success, name='register_success'),
    path('activate/<str:uid>/<str:token>/', views_account.activate, name='activate'),

    
]

recommendations_for_webtoons/recommendations_for_webtoons/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("recommendationapp.urls"))
]
    

recommendations_for_webtoons/recommendationapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


# Create your models here.

# HeidiSQL 통해서
# db_info.conf 문서 참조하여 로그인하시면 생성된 DB를 볼 수 있습니다.

class Detail(models.Model):
    title_id = models.CharField(max_length=15, blank=True, null=True)
    title = models.CharField(max_length=20, blank=True, null=True)
    website = models.CharField(max_length=10, blank=True, null=True)
    story = models.TextField(blank=True, null=True)
    
    class Meta:
        managed = False
        db_table = 'detail'


class Artist(models.Model):
    name = models.CharField(max_length=255, default='', null=True, blank=True)


class Genre(models.Model):
    name = models.CharField(max_length=255, default='', null=True, blank=False)  # 장르 이름에 blank 없앴습니다!
    count = models.IntegerField(default=0, blank=True, null=True)
    
    def disp_artwork(self):
        print(self.name)
        print(Rel_gr_aw.objects.filter(r_genre__name=self.name).count())
        return Rel_gr_aw.objects.filter(r_genre__name=self.name)[1:13]


class Publisher(models.Model):
    name = models.CharField(max_length=255, default='', null=True, blank=True)
    count = models.IntegerField(default=0, blank=True, null=True)


class Artwork(models.Model):  # DB Table 첫글자 대문자로 맞추겠습니다. 이하 컬럼 소문자.
    token = models.CharField(max_length=1, default='')
    uid = models.IntegerField(default='0')
    title = models.CharField(max_length=255, default='', null=True, blank=True)
    #    외래키
    # on_delete = models.PROTECT : 장르가 지워질 때, 장르 아래 Artwork가 존재하면 지워지지 않게 함.
    publisher = models.ForeignKey(Publisher, on_delete=models.PROTECT, related_name='publish', blank=True, null=True)
    
    rating = models.FloatField(default=0, null=True, blank=True)  # 평점
    
    # story, url => 255자 이상 길 수 있으므로 textfield 지정
    story = models.TextField(default='', null=True, blank=True)
    url = models.TextField(default='', null=True, blank=True)
    thumbnail_url = models.TextField(default='', null=True, blank=True)
    
    # 일반 os에서 경로 255자 제한이므로, 다중 행을 다룰 이유 또한 없으므로.
    path_thumb = models.CharField(max_length=255, default='', null=True, blank=True)
    
    # 참 거짓 필드
    enable = models.BooleanField(default=True)
    
    class Meta:
        ordering = ['title']  # 기본적으로 db에서 불러올 때 title 순으로 정렬
        unique_together = ['token', 'uid']

    def get_id(self):
        return f"{self.token}_{self.uid}"

    def temp_thumbpath(self):
        return f'https://set.ramdatech.online/static/static/thumbs/{self.token}_{self.uid}.jpg'
    
    def get_rels(self):
        return Sim_th_th.objects.filter(r_artwork1=self.id)
    
# ============================================================================
# ============================================================================
# 다대다 필드 구현 : manytomanyField 사용치 않고 직접 구현하겠습니다.
# Through model을 포함하여 직접 정의합니다.

class Rel_ar_aw(models.Model):  # N개의 작가들이 N개의 작품에 대해 붙을 수 있으므로, 다대다 관계
    r_artist = models.ForeignKey(Artist, on_delete=models.PROTECT, related_name='ar_aw', blank=True, null=True)
    r_artwork = models.ForeignKey(Artwork, on_delete=models.PROTECT, related_name='aw_ar', blank=True, null=True)
    type = models.CharField(max_length=255, default='', null=True, blank=True)
    
    # 해당 작가-작품이 어떤 관계인지(글작가, 그림작가, 원작자, 배급사) 타입 기재
    
    class Meta:
        ordering = ['r_artist__name', 'r_artwork__title', '-type']
        # 일반적으로 산출할 때, 한 작가의 같은 작품을 우선하여 type 순으로 가져옵니다.


class Rel_gr_aw(models.Model):  # 장르 - 작품 다대다 관계필드
    # 장르 또한 다중장르 작업을 진행하기로 하였으므로. 위와 동일
    r_genre = models.ForeignKey(Genre, on_delete=models.PROTECT, related_name='gr_aw', blank=True, null=True)
    r_artwork = models.ForeignKey(Artwork, on_delete=models.PROTECT, related_name='aw_gr', blank=True, null=True)
    
    class Meta:
        ordering = ['r_artwork__title']
        # 일반적으로 산출할 때, 숫자순/알파벳순/가나다순으로 가져옵니다.


class Sim_st_st(models.Model):  # story 유사도
    r_artwork1 = models.ForeignKey(Artwork, on_delete=models.PROTECT, related_name='st1_st2', blank=True, null=True)
    r_artwork2 = models.ForeignKey(Artwork, on_delete=models.PROTECT, related_name='st2_st1', blank=True, null=True)
    similarity = models.FloatField(default=0, null=True, blank=False)
    
    class Meta:
        ordering = ['-similarity']

    def get_score(self):
        return str(int(self.similarity*100))

class Sim_th_th(models.Model):
    r_artwork1 = models.ForeignKey(Artwork, on_delete=models.PROTECT, related_name='th1_th2', blank=True, null=True)
    r_artwork2 = models.ForeignKey(Artwork, on_delete=models.PROTECT, related_name='th2_th1', blank=True, null=True)
    similarity = models.FloatField(default=0, null=True, blank=False)
    
    class Meta:
        ordering = ['-similarity']

    def get_score(self):
        return str(int(self.similarity*1000))[1:]

# ============================================================================
# 회원가입관련 DB
# ============================================================================

class UserManager(BaseUserManager):
    def create_user(self, username=None, email=None, password=None):
        if not email:
            raise ValueError("must have user email")
        if not username:
            raise ValueError("must have user username")
        user = self.model(
            username=username,
            email=self.normalize_email(email)
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    

class Member(AbstractBaseUser):
    uid = models.AutoField(primary_key=True)
    email = models.EmailField(max_length=50, null=False, blank=False, unique=True)
    username = models.CharField(default='', max_length=50, null=False, blank=False)
    
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    
    objects = UserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    
    def __str__(self):
        return self.username
    
    def has_perm(self, perm, obj=None):
        return self.is_admin
    
    def has_module_perms(self, app_lable):
        return True


class Userprofile(models.Model):
    member = models.ForeignKey(Member, on_delete=models.PROTECT, related_name='user_profile', null=False)
    nickname = models.CharField(max_length=10, null=True, blank=False)
    gender = models.BooleanField(null=False, blank=False)
    date_birth = models.DateTimeField(null=False, blank=False)
    create_date = models.DateTimeField(auto_now_add=True)


class Searching_record(models.Model):
    user = models.ForeignKey(Member, on_delete=models.PROTECT, related_name='user_searching')
    record = models.CharField(max_length=50, null=True, blank=True)


class Luv_user_ar(models.Model):
    user = models.ForeignKey(Member, on_delete=models.PROTECT, related_name='luv_user_artwork')
    artwork = models.ForeignKey(Artwork, on_delete=models.PROTECT, related_name='luv_artwork_user')
    score = models.IntegerField(default=0, null=True, blank=False)


class Viewing_record(models.Model):
    user = models.ForeignKey(Member, on_delete=models.PROTECT, related_name='vw_user_artwork')
    artwork = models.ForeignKey(Artwork, on_delete=models.PROTECT, related_name='vw_artwork_user')

# ============================================================================
# ============================================================================

recommendations_for_webtoons/recommendationapp/views.py
# from .parser import
import json
from django.shortcuts import render
from .models import *
from .views_datamanage import *
from django.db import transaction
from collections import Counter
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, Http404
from django.template.loader import render_to_string
from .parser import *


@csrf_exempt
def manage_data(request):
    # http://127.0.0.1:8000/manage_data
    # 본 페이지 들어가시면 DB 제어할 수 있는 버튼 뜹니다.
    # 한번 누르고 기다리면 진행되며, alert 팝업으로 완료 여부가 출력됩니다.
    
    # 본 서버 데이터 內 작품 약 3700개. 작가 4k명 이상 집계.
    
    indicator = request.POST.get('indicator')
    if indicator == "delete_all_data":
        clear_db()
        result = {'response': 'complete'}
        return HttpResponse(json.dumps(result), content_type="application/json")

    elif indicator == "download_all_data":
        write_pub()
        write_baseinfo()
        Pub = {i.name : i for i in Publisher.objects.all()}
        write_artwork(Pub)
        gl = {i.name : i for i in Genre.objects.all()}
        al = {i.name : i for i in Artist.objects.all()}
        wl = {i.token+"%%%"+str(i.uid) : i for i in Artwork.objects.all()}
        write_rel(gl, al, wl)
        write_thumbs_rel()
        write_storys_rel()
        result = {'response': 'complete'}
        return HttpResponse(json.dumps(result), content_type="application/json")
    
    elif indicator == "read_genre":
        model = Genre.objects.all()
        html = render_to_string('./__manage/__genre_table.html', {'data': model})
        result = {'response': 'complete', 'html':html}
        return HttpResponse(json.dumps(result), content_type="application/json")

    return render(request, "./__manage/data.html", {}) # app 내의 templete 폴더 참조


def testpage(request):
    # http://localhost:8000/testpage
    with transaction.atomic():
        sim_bulk_crt = find_story_similarity()
        Sim_st_st.objects.bulk_create(sim_bulk_crt)
        
    data = {'pack' : {'':''}} # front로 데이터를 던지기 위해 pack (body.html 참조)
    return render(request, "./__test/__learn.html", data) # app 내의 templete 폴더 참조

recommendations_for_webtoons/recommendationapp/templates/__manage/data.html
{% extends "../base.html" %}
{% load static %}

{% comment %} 상위 폴더. body.html을 상속받아 이어갑니다. {% endcomment %}
{% load static %}

{% comment %} 크롬으로 들어가서 개발자 도구로 보면, url 호출 부분이 정식 url로 바뀌어 있습니다. {% endcomment %}

{% block body %}
<div class='row m-5'>
    <div class='col m-2'> 
        <table class="table">
            <thead>
                <tr>
                <th scope="col">분류</th>
                <th scope="col">기능명</th>
                <th scope="col">기능상세</th>
                <th scope="col">입력</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Delete</td>
                    <td>전체 삭제</td>
                    <td>DB의 전체 데이터를 삭제합니다.</td>
                    <td>
                        <button type="button" id='del_data' class="btn btn-sm btn-warning my-0 py-0 w-100">데이터 소거</button>
                    </td>
                </tr>
                <tr>
                    <td>Write</td>
                    <td>전체 쓰기</td>
                    <td>본서버 DB로부터 전체 데이터를 받아옵니다.</td>
                    <td>
                        <button type="button" id="get_data" class="btn btn-sm btn-warning my-0 py-0 w-100">API 불러오기</button>
                    </td>
                </tr>
                <tr>
                    <td> </td>
                    <td> </td>
                    <td> </td>
                    <td> </td>
                </tr>
                <tr>
                    <td>Read</td>
                    <td>장르 정보 읽기</td>
                    <td>로컬 DB로부터 장르 데이터를 받아옵니다.</td>
                    <td>
                        <button type="button" id="read_genre" class="btn btn-sm btn-warning my-0 py-0 w-100">장르 불러오기</button>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class='col m-2'> 
        <table id='target_table' class="table">
            <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">First</th>
                <th scope="col">Last</th>
                <th scope="col">Handle</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                <td>Jacob</td>
                <td>Jacob</td>
                <td>Thornton</td>
                <td>@fat</td>
                </tr>
                <tr>
                <td>Jacob</td>
                <td colspan="2">Larry the Bird</td>
                <td>@twitter</td>
                </tr>
            </tbody>
        </table>
    </div>
    
</div>
{% endblock %}


{% block scripts %}
    var submenu_status = false;
    var ajax_url = "{% url 'rcmd:md' %}"

    function request_ajax(url, data_dict) {
            $.ajax({
                url:url,
                type:'POST',
                async:false,
                data:data_dict,
                success: function (response) {
                        result = response
                        },
            error: function (e) {
                    alert("connenction error")
                    result = "error"
                    }
            });
        return result;
    }

    $(document).on("click","#del_data",function(){
        data = {'indicator' : 'delete_all_data'}
        var res = request_ajax(ajax_url, data)
        if (res.response === 'complete') {
            alert('데이터 삭제 완료')
        } else {
            alert("통신 오류")
        }
    })

    $(document).on("click","#get_data",function(){
        data = {'indicator' : 'download_all_data'}
        var res = request_ajax(ajax_url, data)
        if (res.response === 'complete') {
            alert('데이터 등재 완료')
        } else {
            alert("통신 오류")
        }
    })

    $(document).on("click","#read_genre",function(){
        data = {'indicator' : 'read_genre'}
        var res = request_ajax(ajax_url, data)
        if (res.response === 'complete') {
            alert('불러오기 완료')
            $('#target_table').replaceWith(res.html)
        } else {
            alert("통신 오류")
        }
    })
{% endblock %}